apiVersion: v1
kind: Template
labels:
  demo: template-buildimage
metadata:
  annotations:
    description: template-buildimage
  name: ${APP_NAME}
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: ${APP_NAME}
    labels:
      app: ${APP_NAME}
      application: ${APP_NAME}
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ${APP_NAME}:latest
    source:
      contextDir: ${CONTEXTDIR_TEMPL}
      git:
        ref: ${GIT_REF}
        uri: ${GIT_URI}
      type: Git
    strategy:
      sourceStrategy:
        env:
        - name: MI_ENVIRONMENT
          value: eliminar
        from:
          kind: ImageStreamTag
          name: php:7.2
          namespace: openshift
      type: Source
    triggers:
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
parameters:
- displayName: Application name
  name: APP_NAME
  value: miphp
  required: true
- description: Git source URI for application
  displayName: Git source repository
  name: GIT_URI
  value: https://github.com/gditrani269/test-php.git
- displayName: Git branch/tag reference
  name: GIT_REF
  value: master
  required: true
- displayName: ContexDir
  name: CONTEXTDIR_TEMPL
  value: 
  required: true
