apiVersion: v1
kind: Template
labels:
  demo: ${APP_NAME}
metadata:
  annotations:
    description: template route
  name: ${APP_NAME}
objects:
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: ${APP_NAME}
      application: ${APP_NAME}
    name: ${APP_NAME}
  spec:
    to:
      kind: Service
      name: ${APP_NAME}
      weight: 100
parameters:
- displayName: Application name
  name: APP_NAME
  value: miphp
  required: true
